#cloud-config
timezone: America/Argentina/Buenos_Aires

# incus launch images:debian/13/cloud lhome-docker01 -c security.nesting=true --config=user.user-data="$(cat ~/cloud-init/docker.yml)"
users:
  - name: cmiranda
    ssh-authorized-keys:
      - ssh-ed25519 AAAAC3NzaC1lZDI1NTE5AAAAIOmWoYmXFKdbDYqhTzxgAEyfXNuihMf8FpGlBN5uxF40 cmiranda@ed25519
    sudo: ["ALL=(ALL) NOPASSWD:ALL"]
    groups: sudo,docker
    shell: /bin/bash

packages:
  - aptitude
  - wget
  - rsync
  - curl
  - tmux
  - vim
  - nano
  - sudo
  - less
  - gpg
  - pbzip2
  - htop
  - whois
  - git
  - pigz
  - tree
  - apt-transport-https
  - ca-certificates
  - openssh-server

runcmd:
  # Docker installation
  - sleep 15
  - install -m 0755 -d /etc/apt/keyrings
  - curl -fsSL https://download.docker.com/linux/debian/gpg -o /etc/apt/keyrings/docker.asc
  - chmod a+r /etc/apt/keyrings/docker.asc
  - echo "deb [arch=$(dpkg --print-architecture) signed-by=/etc/apt/keyrings/docker.asc] https://download.docker.com/linux/debian $(. /etc/os-release && echo "$VERSION_CODENAME") stable" > /etc/apt/sources.list.d/docker.list
  - apt-get update
  - apt-get install -y docker-ce docker-ce-cli containerd.io docker-buildx-plugin docker-compose-plugin
  # Docker daemon configuration
  - mkdir -p /etc/docker
  - |
    cat > /etc/docker/daemon.json <<EOF
    {
      "mtu": 1450,
      "log-driver": "json-file",
      "log-opts": {
        "max-size": "10m",
        "max-file": "3"
      }
    }
    EOF
  # User configuration
  - sed -i 's/^#force_color_prompt=yes/force_color_prompt=yes/' /etc/skel/.bashrc
  - sed -i 's/\\\\[\\\033\[01;32m\\\\]/\\\\[\\\033[01;36m\\\\]/' /etc/skel/.bashrc
  - cat /etc/skel/.bashrc > /root/.bashrc
  - cat /etc/skel/.bashrc > /home/cmiranda/.bashrc
